Laboratory work #2, Anna Egorova - 21FPL1
fipl-hse/2022-2-level-labs pull request #103
Opened 2022-10-09 19:03 UTC by chezar0

2022-10-10 06:04 UTC, artyomtugaryov requested changes
Hello, @chezar0 ! As a reminder, the deadline for the second lab is October 21th and you have less than 2 weeks to complete it. Please hurry.

2022-10-10 06:04 UTC, artyomtugaryov commented on lab_1_keywords_tfidf/main.py
> -    In case of corrupt input arguments, None is returned
revert

2022-10-17 06:12 UTC, artyomtugaryov requested changes
Hey @chezar0 ! As a reminder, the deadline for the second lab is October 21st and you have less than a week to complete it. Please hurry

2022-10-20 07:17 UTC, artyomtugaryov requested changes

2022-10-20 07:17 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +        i = i.split()
looks like this code has not effect

2022-10-20 07:17 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +            phrase = r'(\b\w*\b)(?<= ' + candidate[0][-1] + ')(?= ' + candidate[-1][0] + ')'
use f string

2022-10-20 14:34 UTC, chezar0 commented on lab_2_keywords_cooccurrence/main.py
> +        i = i.split()
fixed

2022-10-24 12:19 UTC, closed without merging