Laboratory work #2, Bushueva Nataliya - 21FPL2
fipl-hse/2022-2-level-labs pull request #107
Opened 2022-10-11 10:57 UTC by NataliaBush

2022-10-17 05:50 UTC, artyomtugaryov requested changes
Hey @NataliaBush! As a reminder, the deadline for the second lab is October 21st and you have less than a week to complete it. Please hurry

2022-10-20 08:33 UTC, artyomtugaryov requested changes

2022-10-20 08:33 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +        if word not in signs:
try to use str.replace

2022-10-20 13:17 UTC, NataliaBush commented on lab_2_keywords_cooccurrence/main.py
> +        if word not in signs:
![image](https://user-images.githubusercontent.com/113165748/196958764-1a2bdbfa-4a2e-44d7-99a9-a777ca3c4a25.png)
Команду написала, оно работает и выдает правильный результат, но тесты перестает проходить, хотя все, по крайней мере на первый взгляд, правильно. Выдает даже такую ошибку (в тестах), что знаки пунктуации не удаляются. Может, оставить так, как было?

2022-10-24 12:27 UTC, closed without merging