Laboratory work #2, Alyona Gosteva - 21FPL1
fipl-hse/2022-2-level-labs pull request #125
Opened 2022-10-17 16:39 UTC by Gostaa

2022-10-18 07:56 UTC, artyomtugaryov commented
Hey @Gostaa! As a reminder, the deadline for the second lab is October 21st and you have less than a week to complete it. Please hurry

2022-10-29 11:28 UTC, artyomtugaryov requested changes
Nothing to review(

2022-11-04 12:36 UTC, artyomtugaryov requested changes
Nothing to review

2022-11-08 07:52 UTC, artyomtugaryov requested changes
Please, fix conflicts

2022-11-08 07:52 UTC, artyomtugaryov commented on lab_1_keywords_tfidf/target_score.txt
> +6
!

2022-11-14 14:31 UTC, artyomtugaryov requested changes

2022-11-14 14:31 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/start.py
> +from main import extract_phrases, extract_candidate_keyword_phrases, calculate_frequencies_for_content_words, \
`from lab_2_keywords_cooccurrence.main` ...

2022-11-14 14:31 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +            if word in word_scores:
reverse the condition and return `None`

2022-11-15 05:32 UTC, artyomtugaryov requested changes

2022-11-15 05:32 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +    for string in phrases:
do it in one line

2022-11-16 14:48 UTC, Gostaa commented on lab_2_keywords_cooccurrence/start.py
> +from main import extract_phrases, extract_candidate_keyword_phrases, calculate_frequencies_for_content_words, \
done

2022-11-16 15:37 UTC, Gostaa commented on lab_2_keywords_cooccurrence/main.py
> +    for string in phrases:
done

2022-11-16 15:37 UTC, Gostaa commented on lab_2_keywords_cooccurrence/main.py
> +            if word in word_scores:
done

2022-11-17 14:49 UTC, artyomtugaryov approved these changes

2022-11-17 14:49 UTC, closed without merging