Laboratory work #2, Polina Zhilina - 21FPL2
fipl-hse/2022-2-level-labs pull request #127
Opened 2022-10-18 11:12 UTC by polyamba

2022-10-19 13:46 UTC, artyomtugaryov requested changes

2022-10-19 13:46 UTC, artyomtugaryov commented on seminars/practice_2_strings.py
> +# """
revert

2022-10-19 13:46 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +    phrase_list = [phrase.strip() for phrase in phrase_list if phrase.strip()]
return directly this list. use construction from https://www.youtube.com/watch?v=ZBv-G4vxxyc

2022-10-19 13:46 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +                if len(phrase_tpl) != 0:
just `if  phrase_tpl`

2022-10-19 13:46 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +    for word in word_degrees.keys():
just `for word in word_degrees`

2022-10-19 13:46 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +        if word not in word_frequencies.keys():
just `if word not in word_frequencies`

2022-10-19 13:46 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/start.py
> +    # assert RESULT, 'Keywords are not extracted'
revert

2022-10-20 08:32 UTC, artyomtugaryov reviewed
please, fix comments

2022-10-20 12:57 UTC, polyamba commented on seminars/practice_2_strings.py
> +# """
done

2022-10-25 08:42 UTC, artyomtugaryov requested changes

2022-10-25 08:42 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +        for w in phrase:
bad name of the variable

2022-10-25 08:42 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +        phrase_score = float(0)
0.0

2022-10-25 08:42 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +
revert

2022-10-29 11:30 UTC, artyomtugaryov requested changes
Fix merge conflicts. If you have questions about this process - ask me

2022-11-04 12:35 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +    if not (phrases and isinstance(phrases, list) and stop_words and isinstance(stop_words, list)):
this condition is confusing. It will be better if you write using the 'or' operator: `not  phrases or not  isinstance(phrases, list) ...`

2022-11-04 12:36 UTC, artyomtugaryov requested changes

2022-11-04 12:36 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +                tuple_lst.append(word)
use  the `continue` operator and remove the `else` word

2022-11-21 07:59 UTC, artyomtugaryov requested changes

2022-11-21 07:59 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +            if word not in word_degrees.keys():
```suggestion
            if word not in word_degrees:
```

2022-11-21 12:56 UTC, closed without merging