Laboratory work #3, Lopatko Yulia - 21FPL1
fipl-hse/2022-2-level-labs pull request #142
Opened 2022-11-01 11:14 UTC by lazykosti

2022-11-08 13:24 UTC, lazykosti commented
problem with solving unittests' failing (it seems like those tests that i didn't write are failing, for example, steps 8.2-8.4)

2022-11-08 13:51 UTC, artyomtugaryov commented
Write to our chat about problem with tests

2022-11-15 05:51 UTC, artyomtugaryov requested changes

2022-11-15 05:51 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +        for index, element in enumerate(tokens):
read about `start` argument

2022-11-15 05:51 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +                for pair in [(tokens[index + i], tokens[index + j])]:
looks like this for is unnecessary - iteration is always in one element

2022-11-15 05:51 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +                self._matrix[0].append(vertex)
again

2022-11-21 10:23 UTC, artyomtugaryov requested changes

2022-11-21 10:23 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +        encoded_tokens = tuple(self._word2id.values())
I think, it is a wrong implementation.

2022-11-21 10:23 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +            for number in self._id2word:
why don't you just do `tokens.append(self._id2word[number])` ? Why do you need this loop?

2022-11-24 15:45 UTC, artyomtugaryov requested changes

2022-11-24 15:45 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +            for number in self._id2word:
?

2022-11-28 08:39 UTC, closed without merging