Laboratory work #3, Egorova Anna - 21FPL1
fipl-hse/2022-2-level-labs pull request #160
Opened 2022-11-17 12:55 UTC by chezar0

2022-11-21 06:14 UTC, artyomtugaryov requested changes

2022-11-21 06:14 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +        if self._matrix[self._vertexes.index(vertex1)][self._vertexes.index(vertex2)] == 1 and\
split into two `ifs`

2022-11-21 12:35 UTC, artyomtugaryov requested changes

2022-11-21 12:35 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +            if i not in self._id2word.keys():
```suggestion
            if i not in self._id2word:
```

2022-11-22 08:31 UTC, chezar0 commented on lab_3_keywords_textrank/main.py
> +        self.stop_words = stop_words
done

2022-11-22 08:31 UTC, chezar0 commented on lab_3_keywords_textrank/main.py
> +        for i in encoded_tokens:
done

2022-11-22 08:32 UTC, chezar0 commented on lab_3_keywords_textrank/main.py
> +        if self._matrix[self._vertexes.index(vertex1)][self._vertexes.index(vertex2)] == 1 and\
done

2022-11-22 08:32 UTC, chezar0 commented on lab_3_keywords_textrank/main.py
> +            if i not in self._id2word.keys():
done

2022-11-24 15:43 UTC, artyomtugaryov requested changes

2022-11-24 15:43 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +        for i in tokens:
do it in one line

2022-11-24 17:46 UTC, chezar0 commented on lab_3_keywords_textrank/main.py
> +        for i in tokens:
done

2022-11-27 11:27 UTC, artyomtugaryov approved these changes

2022-11-27 11:27 UTC, closed without merging