Laboratory work #3, Polina Zhilina - 21FPL2
fipl-hse/2022-2-level-labs pull request #169
Opened 2022-11-21 13:16 UTC by polyamba

2022-11-24 13:53 UTC, artyomtugaryov requested changes

2022-11-24 13:53 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +
revert

2022-11-24 13:53 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/start.py
> +    assert RESULT, 'Keywords are not extracted'
revert

2022-11-24 13:53 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/target_score.txt
> +10
revert

2022-11-24 13:53 UTC, artyomtugaryov commented on lab_3_keywords_textrank/README.md
> +
revert

2022-11-24 13:53 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +        tokens = tuple(clean_text.split())
return the tuple without creating a variable

2022-11-24 13:53 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +        return no_stopwords
again. Do not create unnecessary variable

2022-11-24 13:53 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +        for token in tokens:
strange implementation. Use enumerate

2022-11-24 13:53 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +        for token in tokens:
for + cast to tuple - in one line. Use tuple comprehension

2022-11-24 13:53 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +        for i in self._matrix:
how to make it faster

2022-11-28 08:58 UTC, demid5111 approved these changes

2022-11-28 08:58 UTC, closed without merging