Laboratory work #4, Alina Aisina - 21FPL1
fipl-hse/2022-2-level-labs pull request #185
Opened 2022-12-01 21:30 UTC by itsaisina

2022-12-05 14:43 UTC, artyomtugaryov commented on lab_4_summarization_textrank/main.py
> +        super().__init__()
Please, check https://github.com/fipl-hse/2022-2-level-labs/blob/9045abee06da422d19ff5ed4bcb9fbb5cf587b30/lab_4_summarization_textrank/README.md?plain=1#L216

2022-12-05 14:44 UTC, artyomtugaryov requested changes

2022-12-05 14:44 UTC, artyomtugaryov commented on lab_4_summarization_textrank/start.py
> +    # assert RESULT, 'Summaries are not extracted'
revert

2022-12-07 06:16 UTC, itsaisina commented on lab_4_summarization_textrank/start.py
> +    # assert RESULT, 'Summaries are not extracted'
done

2022-12-12 10:59 UTC, artyomtugaryov requested changes

2022-12-12 10:59 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +import csv
revert

2022-12-12 10:59 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +
revert

2022-12-12 10:59 UTC, artyomtugaryov commented on lab_3_keywords_textrank/start.py
> -
revert

2022-12-12 10:59 UTC, artyomtugaryov commented on lab_3_keywords_textrank/target_score.txt
> -8
revert

2022-12-12 10:59 UTC, artyomtugaryov commented on lab_4_summarization_textrank/main.py
> +        super().__init__()
perfect

2022-12-13 12:56 UTC, itsaisina commented on lab_3_keywords_textrank/main.py
> +import csv
done

2022-12-13 12:56 UTC, itsaisina commented on lab_3_keywords_textrank/main.py
> +
done

2022-12-13 12:56 UTC, itsaisina commented on lab_3_keywords_textrank/start.py
> -
done

2022-12-13 12:56 UTC, itsaisina commented on lab_3_keywords_textrank/target_score.txt
> -8
done

2022-12-15 14:31 UTC, artyomtugaryov approved these changes

2022-12-15 14:34 UTC, artyomtugaryov approved these changes

2022-12-16 12:55 UTC, demid5111 requested changes

2022-12-16 12:55 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
>      :param other_sequence: a sequence of items
reply contains one sentence per text

2022-12-16 12:55 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +        jaccard_index = similar / (len(set(sequence) | set(other_sequence)))
count similar with sets as well

2022-12-16 12:55 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +                self._matrix.append([calculate_similarity(vertex.get_encoded(), other.get_encoded())
double computations?

2022-12-23 11:11 UTC, merged