Laboratory work #4, Chekmareva Kristina - 21FPL1
fipl-hse/2022-2-level-labs pull request #189
Opened 2022-12-02 15:17 UTC by kschekmareva

2022-12-05 14:45 UTC, artyomtugaryov commented
Nothing to review(

2022-12-12 10:57 UTC, artyomtugaryov requested changes

2022-12-12 10:57 UTC, artyomtugaryov commented on lab_1_keywords_tfidf/start.py
> +
revert

2022-12-12 10:57 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +                           open(keywords_path, 'r', encoding='utf-8') as keywords_to_read):
revert

2022-12-12 10:57 UTC, artyomtugaryov commented on lab_3_keywords_textrank/start.py
> +from lab_3_keywords_textrank.main import extract_pairs, TextPreprocessor, \
revert

2022-12-15 14:43 UTC, artyomtugaryov requested changes

2022-12-15 14:43 UTC, artyomtugaryov commented on lab_4_summarization_textrank/main.py
> +class SimilarityMatrix():
?revert

2022-12-16 13:02 UTC, demid5111 requested changes

2022-12-16 13:02 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +    intersection = list(set(sequence) & set(other_sequence))
what is this operation about?

2022-12-16 13:02 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +        summa = 0
rename to something not translit

2022-12-16 13:03 UTC, demid5111 commented on lab_4_summarization_textrank/start.py
> +    COMPLETED_SUMMARY = text_rank.make_summary(5)
summary not longer than 20% of text

10 -> 2

2022-12-23 11:46 UTC, closed without merging