Laboratory work #4, Pershina Olga - 21FPL1
fipl-hse/2022-2-level-labs pull request #190
Opened 2022-12-02 15:17 UTC by OlyaP12

2022-12-05 14:45 UTC, artyomtugaryov commented
nothing to review(

2022-12-12 10:55 UTC, artyomtugaryov requested changes
What about 6?8?10?

2022-12-12 10:55 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +
revert

2022-12-12 10:55 UTC, artyomtugaryov commented on lab_3_keywords_textrank/start.py
> -
revert

2022-12-13 19:21 UTC, OlyaP12 commented on lab_3_keywords_textrank/start.py
> -
done

2022-12-13 19:21 UTC, OlyaP12 commented on lab_3_keywords_textrank/main.py
> +
done

2022-12-16 13:16 UTC, demid5111 requested changes

2022-12-16 13:16 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +    _preprocessed: tuple[str, ...]
why?

2022-12-16 13:16 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +        for idx, token in enumerate(new_tokens, 1000 + len(self._word2id)):
last_id

2022-12-16 13:16 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +        if not isinstance(tokens, tuple):
use check_object_and_type

2022-12-16 13:16 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +    if not isinstance(sequence, (list, tuple)) or not isinstance(other_sequence, (list, tuple)):
.

2022-12-23 11:47 UTC, closed without merging