Laboratory work #4, Menyalshchikov Timur - 21FPL1
fipl-hse/2022-2-level-labs pull request #200
Opened 2022-12-07 09:03 UTC by Timur20033

2022-12-12 10:48 UTC, artyomtugaryov approved these changes
What about 10?

2022-12-16 12:09 UTC, demid5111 requested changes

2022-12-16 12:09 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +        sentences = dogs.split("@")
improve

2022-12-16 12:09 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +        for idx, token in enumerate(new_tokens, 1000 + len(self._word2id)):
own instance attribute - 1000

2022-12-16 12:09 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +        summa = 0
normal name

2022-12-23 12:11 UTC, closed without merging