Laboratory work #4, Zhilina Polina - 21FPL2
fipl-hse/2022-2-level-labs pull request #202
Opened 2022-12-08 15:37 UTC by polyamba

2022-12-12 10:44 UTC, artyomtugaryov requested changes
Nothing to review:(

2022-12-15 14:27 UTC, artyomtugaryov requested changes

2022-12-15 14:27 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/target_score.txt
> +10
revert

2022-12-15 14:27 UTC, artyomtugaryov commented on lab_4_summarization_textrank/main.py
> +        self.last_id = 0
INCUPSULATION

2022-12-15 14:27 UTC, artyomtugaryov commented on lab_4_summarization_textrank/main.py
> +        # for token, idx in zip(tokens, range(1000, 1000 + len(tokens))):
remove

2022-12-16 10:55 UTC, polyamba commented on lab_4_summarization_textrank/main.py
> +        # for token, idx in zip(tokens, range(1000, 1000 + len(tokens))):
done

2022-12-23 12:30 UTC, closed without merging