Laboratory work #4, Sofya Kuzmichyova - 21FPL2
fipl-hse/2022-2-level-labs pull request #203
Opened 2022-12-08 18:48 UTC by sophiek19

2022-12-12 10:39 UTC, artyomtugaryov requested changes

2022-12-12 10:39 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +import random
revert to main

2022-12-15 14:24 UTC, artyomtugaryov requested changes

2022-12-15 14:24 UTC, artyomtugaryov commented on lab_4_summarization_textrank/main.py
> +def raise_error(obj: Any, type_name: Any, el_type: Any):
the name is bad.

2022-12-15 14:24 UTC, artyomtugaryov commented on lab_4_summarization_textrank/main.py
> +                text = text[text.index(lst[i]) + 1::]
Why do you use the second `:`?

2022-12-16 10:50 UTC, demid5111 requested changes

2022-12-16 10:50 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +    if not (isinstance(obj, type_name) and obj is not True):
open brackets, True?

2022-12-16 10:50 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +    if isinstance(obj, Sequence) and len(obj) != 0:
eliminate Sequence

2022-12-16 10:50 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +        numbers = tuple(set(random.sample(range(1000, 10000), len(words))))
monotonically increase from 1000 to ...

2022-12-16 10:50 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +        self._last = 0
1000

2022-12-23 12:31 UTC, closed without merging