Laboratory work #4, Sofya Kostina - 21FPL2
fipl-hse/2022-2-level-labs pull request #215
Opened 2022-12-11 20:45 UTC by d07l

2022-12-12 09:57 UTC, artyomtugaryov requested changes

2022-12-12 09:57 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +        # Step 8.2
revert

2022-12-12 09:57 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
>          for _ in range(0, self._max_iter):
revert

2022-12-13 18:26 UTC, d07l commented on lab_3_keywords_textrank/main.py
> +        # Step 8.2
done

2022-12-13 18:26 UTC, d07l commented on lab_3_keywords_textrank/main.py
>          for _ in range(0, self._max_iter):
done

2022-12-15 13:10 UTC, artyomtugaryov requested changes

2022-12-15 13:10 UTC, artyomtugaryov commented on requirements.txt
> -
? Revert

2022-12-15 14:01 UTC, d07l commented on requirements.txt
> -
done

2022-12-15 14:55 UTC, artyomtugaryov approved these changes

2022-12-16 11:14 UTC, demid5111 commented on lab_4_summarization_textrank/start.py
> +    print(buddy.reply(QUERY))
demonstrate and handle exceptions

2022-12-23 12:35 UTC, closed without merging