Laboratory work #4, Maxim Matveev - 21FPL1
fipl-hse/2022-2-level-labs pull request #221
Opened 2022-12-14 14:41 UTC by yourMasya

I don't know where I'm going
But I sure know where I've been
Hanging on the promises
In songs of yesterday

And I've made up my mind
I ain't wasting no more time

Here I go again
Here I go again

Though I keep searching for an answer
I never seem to find what I'm looking for
Oh, Lord, I pray
You give me strength to carry on

'Cause I know what it means
To walk along the lonely street of dreams

Here I go again on my own
Goin' down the only road I've ever known
Like a hobo I was born to walk alone

But I've made up my mind
I ain't wasting no more time

Just another heart in need of rescue
Waiting on love's sweet charity
I am gonna hold on
For the rest of my days

'Cause I know what it means
To walk along the lonely street of dreams

Here I go again on my own
Goin' down the only road I've ever known
Like a hobo I was born to walk alone
And I've made up my mind
I ain't wasting no more time

But here I go again
Here I go again
Here I go again
Here I go

And I've made up my mind
I ain't wasting no more time

Here I go again on my own
Goin' down the only road I've ever known
Like a hobo I was born to walk alone
'Cause I know what it means
To walk along the lonely street of dreams

Here I go again on my own
Goin' down the only road I've ever known
Like a hobo I was born to walk alone
I have made up my mind
I ain't wasting no more time

But here I go again
Here I go again
Here I go again
Here I go
Here I go again

2022-12-15 12:48 UTC, artyomtugaryov requested changes
Looks like nothing to review(

2022-12-15 12:49 UTC, artyomtugaryov commented
But the poem is great

2022-12-16 12:15 UTC, demid5111 requested changes

2022-12-16 12:15 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +    blegh
improve

2022-12-16 12:15 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +    blegh
.

2022-12-16 12:15 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +        check_types(text, [str])
check_types(text, str, tuple)

2022-12-16 12:15 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +        check_items_type(encoded_sentence, [tuple], [int])
.

2022-12-16 12:15 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +        for ind, token in enumerate(new_tokens, start=max(1_000, 1_000 + len(self._word2id))):
move to instance attributes

2022-12-16 12:15 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +        for ind, token in enumerate(new_tokens, start=max(1_000, 1_000 + len(self._word2id))):
magic constant

2022-12-16 12:15 UTC, demid5111 commented on lab_4_summarization_textrank/start.py
> +) #NoRelevantTextsError
??

2022-12-16 12:15 UTC, demid5111 commented on lab_4_summarization_textrank/start.py
> +    RESULT = True
[sentence.get_encoded() for sentence in SENTENCES]

2022-12-16 13:06 UTC, yourMasya commented on lab_4_summarization_textrank/main.py
> +    blegh
solved)0))

2022-12-16 13:06 UTC, yourMasya commented on lab_4_summarization_textrank/main.py
> +    blegh
solved)0))

2022-12-16 13:06 UTC, yourMasya commented on lab_4_summarization_textrank/main.py
> +        check_items_type(encoded_sentence, [tuple], [int])
solved)0)).

2022-12-16 13:06 UTC, yourMasya commented on lab_4_summarization_textrank/main.py
> +        for ind, token in enumerate(new_tokens, start=max(1_000, 1_000 + len(self._word2id))):
solved)0))

2022-12-16 13:06 UTC, yourMasya commented on lab_4_summarization_textrank/start.py
> +) #NoRelevantTextsError
solved)0))

2023-01-10 07:39 UTC, closed without merging