Laboratory work #4, Kapitolina Untila - 21FPL1
fipl-hse/2022-2-level-labs pull request #225
Opened 2022-12-14 20:28 UTC by KapitolinaVU

2022-12-15 12:14 UTC, artyomtugaryov commented on lab_3_keywords_textrank/main.py
> +from lab_1_keywords_tfidf.main import (calculate_frequencies, calculate_tf, calculate_tfidf, get_top_n)
The PR name is about the 4 lab. But it is implementation the 3 lab.

2022-12-15 12:14 UTC, artyomtugaryov commented on lab_4_summarization_textrank/main.py
> +
?

2022-12-16 12:48 UTC, demid5111 requested changes

2022-12-16 12:48 UTC, demid5111 commented on lab_3_keywords_textrank/start.py
> +from string import punctuation
discard changes

2022-12-16 12:48 UTC, demid5111 commented on lab_3_keywords_textrank/target_score.txt
> +10
discard changes

2022-12-16 12:48 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +        self._preprocessed: tuple[str, ...] = ()
?

2022-12-16 12:48 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +        splited_text = re.split(r'(?<=[.!?])\s+(?=[A-ZА-Я])', text.replace('\n', ' ').replace('  ', ' '))
only one space?

2022-12-16 12:48 UTC, demid5111 commented on lab_4_summarization_textrank/main.py
> +        for index, token in enumerate(my_tokens, start=1000 + len(self._word2id)):
own attribute of instance and it should be mutated

2023-01-10 07:41 UTC, closed without merging