проба первой лабораторки
fipl-hse/2022-2-level-labs pull request #27
Opened 2022-09-16 08:52 UTC by lazykosti

2022-09-20 05:18 UTC, artyomtugaryov commented on lab_1_keywords_tfidf/main.py
> +with open("Дюймовочка.txt", "r", encoding="utf-8") as f1:
Don't read anything in this file. Please, use the functions in start.py file

2022-09-20 05:18 UTC, artyomtugaryov commented on lab_1_keywords_tfidf/main.py
> +def clean_and_tokenize(text: str):
You mustn't change arguments and types of arguments or anything has already been doing for you. Revert this changes and place implementation of each function after docstring

2022-09-25 16:23 UTC, demid5111 commented on seminars/practice_1_intro.py
> -"""
you should not remove the file (!) return it back

2022-09-25 16:23 UTC, demid5111 commented on requirements.txt
> +black==22.6.0
requirements.txt should not be changed as well. discard changes

2022-09-29 14:20 UTC, artyomtugaryov requested changes

2022-10-03 06:07 UTC, closed without merging