Laboratory work #2, Beryozkin Daniil - 21FPL1
fipl-hse/2022-2-level-labs pull request #84
Opened 2022-10-04 12:59 UTC by danind

2022-10-10 06:37 UTC, artyomtugaryov reviewed
Good. I'm sure you can do the job for 8 and 10 points

2022-10-10 06:37 UTC, artyomtugaryov commented on lab_1_keywords_tfidf/main.py
> -def check_list(user_input: Any, elements_type: type, can_be_empty: bool) -> bool:
You can't change the first lab

2022-10-10 06:37 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +                if word in content_words:
You can take that `if` out of this statement and out of `else` - this is common part.

2022-10-15 17:50 UTC, danind commented
My code can pass all test, but it cannot process all texts in start.py
I guess, there are problems with function «extract_candidate_keyword_phrases_with_adjoining», but I can't solve them :(

2022-10-17 06:39 UTC, artyomtugaryov requested changes
You need to fix start.py for green CI

2022-10-24 12:15 UTC, artyomtugaryov approved these changes

2022-10-24 12:17 UTC, closed without merging