Laboratory work #2, Aisina Alina - 21FPL1
fipl-hse/2022-2-level-labs pull request #90
Opened 2022-10-04 23:47 UTC by itsaisina

2022-10-10 06:24 UTC, artyomtugaryov requested changes

2022-10-10 06:24 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +            elif word not in word_degrees.keys():
```suggestion
            elif word not in word_degrees:
```

2022-10-11 13:44 UTC, itsaisina commented on lab_2_keywords_cooccurrence/main.py
> +            elif word not in word_degrees.keys():
done

2022-10-17 06:26 UTC, artyomtugaryov requested changes

2022-10-17 06:26 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +                if elem == key:
reverse the condition and continue

2022-10-17 06:26 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +            if first_tuple in item1:
reverse condition and continue

2022-10-17 15:57 UTC, itsaisina commented on lab_2_keywords_cooccurrence/main.py
> +            if first_tuple in item1:
Done

2022-10-18 21:02 UTC, itsaisina commented on lab_2_keywords_cooccurrence/main.py
> +def correct_list(list1: Any, type1: Any, empty: bool) -> bool:
done

2022-10-20 08:37 UTC, artyomtugaryov requested changes

2022-10-20 08:37 UTC, artyomtugaryov commented on lab_1_keywords_tfidf/main.py
>      """
too many changes

2022-10-20 08:37 UTC, artyomtugaryov commented on lab_2_keywords_cooccurrence/main.py
> +    return [phrase.strip() for phrase in split_text if phrase.strip() != '']
`!= ''` not needed.  and use := operation

2022-10-20 15:46 UTC, itsaisina commented on lab_1_keywords_tfidf/main.py
>      """
done

2022-10-24 12:43 UTC, closed without merging